<?php

function projectintake_views_api() {
  return array('api' => 3.0);
}

function projectintake_views_default_views() {
  civicrm_initialize();
  $files = file_scan_directory(drupal_get_path('module', 'projectintake'). '/views', '/.inc/');
  $views = array();
  foreach ($files as $filepath => $file) {
    require $filepath;
    if (isset($view)) {
      $views[$view->name] = $view;
    }
  }
  return $views;
}

function projectintake_get_role_ids($roles) {
  $rids = array();
  $available_roles = user_roles();
  foreach($roles as $role) {
    $rid = array_search($role, $available_roles);
    if ($rid !== false) {
      $rids[$rid] = $rid;
    }
  }
  
  return $rids;
}